.Dd May 16, 2022
.Dt nuff 1
.
.Sh NAME
.Nm nuff
.Nd fork of a simple plaintext presentation tool
.
.Sh SYNOPSIS
.Nm
.Op Fl r
.Op Fl f Ar fskip
.Op Fl p Ar pheight
.Op Ar file
.Nm
.Fl v
.
.Sh DESCRIPTION
.Nm
is a simple plain text presentation tool for X.
.Pp
every paragraph represents a slide in the presentation.
.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl f Ar fskip
Skip
.Ar fskip
number of fonts from the font fallback list.
.It Fl p Ar pheight
Set the height of the progress bar to
.Ar pheight
pixels, or
.Cm 0
to disable.
.It Fl r
Swap colors to reverse-video.
.It Fl v
Print version information to stdout and exit.
.El
.Sh USAGE
.Bl -tag -width Ds
.It Em Mouse commands
.Bl -tag -width Ds
.It Sy Button1 | Button5
Go to next slide, if existent.
.It Sy Button3 | Button4
Go to previous slide, if existent.
.El
.It Em Keyboard commands
.Bl -tag -width Ds
.It Sy Escape | q
Quit.
.It Sy r
Reload the slides. Only works on file input.
.It Sy b
Toggle blank
.It Sy Right | Return | Space | l | j | Down | Next | n
Go to next slide, if existent.
.It Sy Left | Backspace | h | k | Up | Prior | p
Go to previous slide, if existent.
.El
.El
.
.Sh FORMAT
The presentation file is made up of at least one paragraph, with an
empty line separating two slides.
Each input line is interpreted literally, except from control characters
at the beginning of lines described as follows:
.Bl -tag -width Ds
.It Sy @
Create individual slide containing the image pointed to by the filename
following the
.Sy @ .
.It Sy #
Ignore this input line.
.It Sy \e
Create input line using the characters following the
.Sy \e
without interpreting them.
.El
.Sh CUSTOMIZATION
.Nm
can be customized by creating a custom config.h and (re)compiling the
source code. This keeps it fast, secure and simple.
.Sh SEE ALSO
.Xr 2ff 1
